### ISSUE TITLE
The Thread context Classloader is not set correctly

### ISSUE THREAD

**Issue by Legion2** [eclipse/microprofile-reactive-messaging#85]
The Thread  context Classloader in a with `@Incoming` annotated message consumer is set to an application classloader. Trying to load providers with spi fails with `java.util.ServiceConfigurationError`.

**Comment by hutchig** [comment]
Hi Legion2, thanks for reporting this - would you like to give a little more information
about the runtime you were using, what sort of 'providers', what spi etc? Also the
exception stack will have lots of information. The TCC maintenance is
often a server/framework managed thing rather than something that is in
a MicroProfile specification.

**Comment by Legion2** [comment]
I'm using OpenLiberty 19.0.0.11 and the SmallRye Reactive Messaging implementation. The `javax.json.bind.spi.JsonbProvider` provider for example is not found:

```
io.smallrye.reactive.messaging.ProcessingException: Exception thrown when calling the method de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService#getMessages
	at io.smallrye.reactive.messaging.AbstractMediator.lambda$initialize$0(AbstractMediator.java:50)
	at io.smallrye.reactive.messaging.AbstractMediator.invoke(AbstractMediator.java:61)
	at io.smallrye.reactive.messaging.SubscriberMediator.lambda$processMethodReturningACompletionStage$6(SubscriberMediator.java:161)
	at io.smallrye.reactive.streams.stages.FlatMapCompletionStageFactory$FlatMapCompletionStage.lambda$apply$0(FlatMapCompletionStageFactory.java:47)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:132)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:501)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:665)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
	at io.reactivex.processors.AsyncProcessor.subscribeActual(AsyncProcessor.java:242)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.smallrye.reactive.streams.utils.ConnectableProcessor.onNext(ConnectableProcessor.java:122)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at io.smallrye.reactive.messaging.SubscriberMediator$1.onNext(SubscriberMediator.java:100)
	at io.smallrye.reactive.streams.utils.WrappedSubscriber.onNext(WrappedSubscriber.java:42)
	at io.reactivex.subscribers.SafeSubscriber.onNext(SafeSubscriber.java:90)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:501)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:665)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
	at io.reactivex.processors.AsyncProcessor.onComplete(AsyncProcessor.java:201)
	at io.smallrye.reactive.streams.utils.CompletionStageToPublisher.lambda$fromCompletionStage$0(CompletionStageToPublisher.java:23)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
	at de.uni_stuttgart.tik.ecs.ecc.connector.ECSInput.executePollActions(ECSInput.java:81)
	at de.uni_stuttgart.tik.ecs.ecc.connector.ECSInput.lambda$2(ECSInput.java:57)
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.run(PolicyTaskFutureImpl.java:715)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl.runTask(PolicyExecutorImpl.java:1135)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl$GlobalPoolTask.run(PolicyExecutorImpl.java:189)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor671.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.smallrye.reactive.messaging.AbstractMediator.lambda$initialize$0(AbstractMediator.java:48)
	... 36 more
Caused by: java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:590)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at javax.json.bind.spi.JsonbProvider.provider(JsonbProvider.java:112)
	at javax.json.bind.JsonbBuilder.create(JsonbBuilder.java:108)
	at de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService.getMessages(ECSComputationService.java:69)
	at de.uni_stuttgart.tik.viplab.websocket_api.ecs.ECSComputationService$Proxy$_$$_WeldClientProxy.getMessages(Unknown Source)
	... 39 more
```

I also opened OpenLiberty/open-liberty#10248 because I don't know who is responsible for fixing the issue. Another related Issue is smallrye/smallrye-reactive-messaging#354.

**Comment by Azquelt** [comment]
We think this is an OpenLiberty issue where the TCCL is set up slightly differently when the application is starting and the CDI extension lifecycle events are being processed compared to when the application has started and is ready to serve requests. I'll close this and continue work under OpenLiberty/open-liberty#10248
